### ISSUE TITLE
Issue - The new key policy will not allow you to update the key policy in the future.

### ISSUE THREAD

**Issue by firke** [trussworks/terraform-aws-cloudtrail#178]
Hi,
Having an issue running module:
```
│ Error: MalformedPolicyDocumentException: The new key policy will not allow you to update the key policy in the future.
│ 
│   with module.aws_cloudtrail.aws_kms_key.cloudtrail,
│   on .terraform/modules/aws_cloudtrail/main.tf line 229, in resource "aws_kms_key" "cloudtrail":
│  229: resource "aws_kms_key" "cloudtrail" {
```

**Definition:**
```
module "aws_cloudtrail" {
  source  = "trussworks/cloudtrail/aws"
  version = "4.3.0"

  s3_bucket_name     = "${var.name}-cloudtrail-logs"
  log_retention_days = 30
  tags = {}
}
```

**Versions:**
Terraform 1.0.0
AWS Provider 3.44 - will test the latest, but don't expect it to fix, nothing in changelog indicates changes to IAM/KMS/Cloudtrail.
Module 4.3.0

Rerunning it did not solve the issue.
Google search mentions having depends_on on IAM resources, will try forking and seeing if replacing data IAM policy with a defined policy fixes this. Will see if any suggestions from [stackoverflow](https://stackoverflow.com/questions/48509193/getting-the-error-in-using-terraform-for-aws-the-new-key-policy-will-not-allow) will work as well, am using a separate user as part of a CI job.
Thanks!

**Comment by dynamike** [comment]
Thanks, we'll have someone look into this next week.

**Comment by cblkwell** [comment]
Hi, I'm trying to look into this -- is it possible your CI user has a policy that restricts it from changing KMS key policies, or only allowing it to change *certain* KMS key policies? I am wondering if this isn't necessarily an issue with the module, but how the module interacts with your environment (which is still something we might be able to fix). Is there any way you could share the IAM policy attached to your CI user (sanitized to remove any sensitive data, obviously)?
