### ISSUE TITLE
encountering error with bucket or kms key

### ISSUE THREAD

**Issue by ethanwllms** [trussworks/terraform-aws-cloudtrail#186]
While using this module for an org-wide cloudtrail, with the use of the trussworks/terraform-aws-logs to compose a bucket for cloudtrail logs.

I encounter the following:

'Error creating CloudTrail: InsufficientEncryptionPolicyException: Insufficient permissions to access S3 bucket *** or KMS key ***'

it seems as if the policy is incorrect for what is needed from cloudtrail, and since the logs module has explicit defaults for cloudtrail, it seems relevant to this repo or that one.

**Comment by ethanwllms** [comment]
For further helpful context, I am attempting to provision an org-wide cloudtrail, and use your aws/logs module to provision the log bucket for cloudtrail (single account) to put logs into. If there is a misuse in that usecase, I will gladly clear this issue out.

**Comment by dynamike** [comment]
Can you provide example terraform code for how you're using this module and the aws-logs module? That'll make it easier to reproduce and respond.

**Comment by ethanwllms** [comment]
Yes, of course!

cloudtrail usage:
`module "aws_cloudtrail" {
  source             = "trussworks/cloudtrail/aws"
  s3_bucket_name     = "org-cloudtrail-logs"
  org_trail          = "true"
  log_retention_days = 120
  trail_name         = "org-cloudtrail"
}`

aws-logs usage:
`module "cloudtrail-log-bucket" {
  source           = "trussworks/logs/aws"
  s3_bucket_name   = "org-cloudtrail-logs"
  s3_bucket_acl    = "log-delivery-write"
  allow_cloudtrail = true
  default_allow    = false

  tags = {
    Application = "Prod"
    Environment = "Management"
  }
}`

**Comment by aussielunix** [comment]
Be sure you are setting `cloudtrail_org_id` to your AWS Organization id when adding the logging bucket.
If you do not know what your Org-id is then `aws organizations describe-organization` and look for `Id`

Example for a multi-account / organization cloudtrail bucket.

```
# Cloudtrail
module "cloudtrail" {
  source                      = "trussworks/cloudtrail/aws"
  version                     = "4.3.0"
  s3_bucket_name              = module.logs.aws_logs_bucket
  log_retention_days          = 7
  org_trail                   = "true"
  key_deletion_window_in_days = "7"
}

# Logging Bucket
module "logs" {
  source  = "trussworks/logs/aws"
  version = "10.3.0"

  s3_bucket_name   = var.logging_bucket
  default_allow    = false
  allow_cloudtrail = true

  cloudtrail_accounts = concat(
    [
      aws_organizations_organization.main.id,
      data.aws_caller_identity.current.account_id
    ],
    aws_organizations_organization.main.accounts[*].id
  )

  cloudtrail_org_id = "o-xxxxxx"
}
```

**Comment by nikolay** [comment]
Thanks, @aussielunix! It worked for me.

**Comment by dynamike** [comment]
@ethanwllms does that resolve your issue as well?
